import { resolve } from 'node:path';
import { chromium } from 'playwright';
const EXE = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const browser = await chromium.launch({ executablePath: EXE, headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await (await browser.newContext({ viewport: { width: 1400, height: 900 } })).newPage();
await page.goto('file://' + resolve(process.env.PT_HTML ?? 'dist/paper-tycoon-solo.html'), { waitUntil: 'domcontentloaded' });
await page.waitForSelector('#setup-start');
await page.click('#setup-start');
await page.waitForSelector('.game canvas');
await page.waitForTimeout(2500);
await page.evaluate(() => window.__pt.forceRoll(3, 4));
await page.click('.actions button:has-text("Roll dice")');
await page.waitForTimeout(9000);
await page.evaluate(() => { document.querySelectorAll('.overlay').forEach((el) => el.remove()); });
await page.screenshot({ path: 'shots/hud-actions.png' });
await page.click('button:has-text("2D")');
await page.waitForTimeout(1200);
await page.screenshot({ path: 'shots/hud-2d.png' });
await browser.close();
