import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
const EXE = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
await mkdir('shots', { recursive: true });
const browser = await chromium.launch({ executablePath: EXE, headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 } });
await ctx.route(/^https?:/, (r) => r.abort());
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_FAILED')) errors.push(m.text()); });
await page.goto('file://' + resolve('dist/paper-tycoon-solo.html'), { waitUntil: 'domcontentloaded' });
await page.waitForSelector('#setup-start');
await page.waitForTimeout(2500);
await page.screenshot({ path: 'shots/tokens-title.png' });
await page.click('#setup-start');
await page.waitForSelector('.game canvas');
await page.waitForTimeout(2500);
const box = await page.locator('.game canvas').boundingBox();
await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
for (let i = 0; i < 6; i++) await page.mouse.wheel(0, -300);
await page.waitForTimeout(1800);
await page.screenshot({ path: 'shots/tokens-close.png' });
// free look from a low side angle
await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 260, box.y + box.height / 2 + 120, { steps: 10 }); await page.mouse.up();
await page.waitForTimeout(1200);
await page.screenshot({ path: 'shots/tokens-side.png' });
await page.evaluate(() => window.__pt.forceRoll(1, 2));
await page.click('.cam-bar button:has-text("Follow")');
await page.click('.actions button:has-text("Roll dice")');
await page.waitForTimeout(2400);
await page.screenshot({ path: 'shots/tokens-walk.png' });
console.log('done; errors:', errors.length ? errors : 'none');
await browser.close();
