import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
const EXE = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
await mkdir('shots', { recursive: true });
const browser = await chromium.launch({ executablePath: EXE, headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 } });
await ctx.route(/^https?:/, (r) => r.abort());
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_FAILED')) errors.push(m.text()); });
await page.goto('file://' + resolve('dist/paper-tycoon-solo.html'), { waitUntil: 'domcontentloaded' });
await page.waitForSelector('#setup-start');
await page.waitForTimeout(2500);
await page.screenshot({ path: 'shots/tokens-title.png' });
await page.click('#setup-start');
await page.waitForSelector('.game canvas');
await page.waitForTimeout(2500);
await page.screenshot({ path: 'shots/tokens-follow.png' });
await page.click('.cam-bar button:has-text("Overview")');
await page.waitForTimeout(1800);
await page.screenshot({ path: 'shots/tokens-overview.png' });
await page.click('.cam-bar button:has-text("Follow")');
// walk 5+6 = 11 → from Go around the corner? 11 = St. Charles (left column): crosses the Jail corner
await page.evaluate(() => window.__pt.forceRoll(5, 6));
await page.click('.actions button:has-text("Roll dice")');
await page.waitForTimeout(3300);
await page.screenshot({ path: 'shots/tokens-corner-1.png' });
await page.waitForTimeout(900);
await page.screenshot({ path: 'shots/tokens-corner-2.png' });
await page.waitForTimeout(2500);
await page.screenshot({ path: 'shots/tokens-side-column.png' });
console.log('done; errors:', errors.length ? errors : 'none');
await browser.close();
