import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
await mkdir('shots', { recursive: true });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 } });
await ctx.route(/^https?:/, (r) => r.abort());
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_FAILED')) errors.push(m.text()); });
await page.goto('file://' + resolve('dist/paper-tycoon-solo.html'), { waitUntil: 'domcontentloaded' });
await page.waitForSelector('#setup-start');
await page.click('.count-row button:has-text("5")');
await page.waitForTimeout(2500);
await page.screenshot({ path: 'shots/big-title.png' });
await page.click('#setup-start');
await page.waitForSelector('.game canvas');
await page.waitForTimeout(2500);
await page.screenshot({ path: 'shots/big-follow.png' });
await page.click('.cam-bar button:has-text("Overview")');
await page.waitForTimeout(1800);
await page.screenshot({ path: 'shots/big-overview.png' });
// zoom in on the Go crowd
await page.click('.cam-bar button:has-text("Follow")');
const box = await page.locator('.game canvas').boundingBox();
await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
for (let i = 0; i < 4; i++) await page.mouse.wheel(0, -300);
await page.waitForTimeout(1800);
await page.screenshot({ path: 'shots/big-crowd.png' });
console.log('done; errors:', errors.length ? errors : 'none');
await browser.close();
